### ISSUE TITLE
How do I pass `Config` to `peppi::game` to only parse metadata?

### ISSUE THREAD

**Issue by ghost** [hohav/peppi#3]
Previously (like 7 months ago) I had the `parse::parse_metadata()` function available, but that branch is currently unavailable. I see in the source code that you've introduced a new public state called `Config`, which supposedly isn't passed anywhere yet. How can I make it with the `const-generics` branch such that I only get the metadata, skipping parsing of frames and making it overall much faster?

**Comment by hohav** [comment]
`Config` is a global singleton; this is a hack due to how hard it is to pass state into Serde serializers. But `skip_frames` is currently only checked during serialization and doesn't skip any parsing work, so toggling it won't speed things up unless you're serializing with Serde.

I do have plans to implement more optimizations for `skip_frames` soon, along with releasing v1.0 now that const generics are stable. In the meanwhile, make sure you're compiling with `--release` as it makes a huge difference.

**Comment by Knarkzel** [comment]
I see, do you know when this will be available? Really awesome work otherwise.

**Comment by hohav** [comment]
Try the latest commit in `const-generics` (cc40843ee036247c42171f98cb78c5eb6697b0c2).

**Comment by hohav** [comment]
I may change things around a bit before I'm happy, but let me know if the general approach works for you.

**Comment by Knarkzel** [comment]
I'll have a look at it. Thanks!

**Comment by hohav** [comment]
Closed by bd1ad05.
